vich_uploader:
    db_driver: orm

    mappings:
        school_image:
            uri_prefix:         '%app.path.school_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.school_image%'
        news_image:
            uri_prefix:         '%app.path.news_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.news_image%'
        class_image:
            uri_prefix:         '%app.path.class_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.class_image%'
